### ISSUE TITLE
Добавить линтер

### ISSUE THREAD

**Issue by TheaseMeanse** [Thenk0/LitminkaApi#102]
# Как же хочется линтер, чтоб код красивый был и внуки гордились

Из вариантов есть ESlint, который после легко интегрируется со всеми популярными CI системами (мы же когда-нибудь запустим автотесты?).
Шо ещё можно - предлагайте.

Требуется поставить и настроить линтер, касательно правил договоримся уже отдельно в процессе настройки

Также после добавления линтера надо будет править предупреждения, но это можно сделать в процессе тестирования, либо уже в патчах

**Comment by Thenk0** [comment]
Голосую за еслинт
