### ISSUE TITLE
Вывод только тайтлов с kodikLink на методах контроллера аниме

### ISSUE THREAD

**Issue by TheaseMeanse** [Thenk0/LitminkaApi#109]
Существует проблема вывода на главную страницу тайтлов, которые не имеют ссылки плеера кодика. Вопрос стоит ли выводить эти тайтлы на главную страницу, к примеру, в методе сезонных тайтлов.

**Comment by Thenk0** [comment]
Булево с дефолтным значением, isWatchable, если выдают тебе false, выдает все тайтлы, в поиск тоже можно добавить, по умолчанию true (хотя как с анонсами быть хз)
