### ISSUE TITLE
Унификация ответа апи для всех методов

### ISSUE THREAD

**Issue by TheaseMeanse** [Thenk0/LitminkaApi#111]
Есть несколько примеров разных ответах. В некоторых ответах данные лежат внутри res.data.data, в некоторых res.data.body, где-то ещё может быть иначе. Стоит унифицировать ответ к одному ключу.

**Comment by Thenk0** [comment]
Поправочка
Axios отдает ответ в формате
```ts
const name = axios.get()
name.data;
```
Т.к мы отдаем в своем ответе тоже поле дата, получается вложенность data

**Comment by Thenk0** [comment]
Ключ ответа предлагаю body, самый универсальный
