### ISSUE TITLE
При повторной привязке аккаунта, прошлая привязка сбрасывается

### ISSUE THREAD

**Issue by ArcKontyR** [Thenk0/LitminkaApi#37]
Когда аккаунт связан с аккаунтом шикимори, повторная его привязка сбрасывает её не сообщая об этом пользователю.
Есть предложение спрашивать пользователя о принудительной перепривязке аккаунта.

**Comment by Thenk0** [comment]
Запретить юзеру привязку шики аккаунта, если он уже привязан, так же как и генерацию ссылки

**Comment by Thenk0** [comment]
Перефразировать комментарий 
```ts
// fix if user integrated another account
if (integrated) {
  await prisma.integration.clear(user.id);
  throw new UnprocessableContentError("Account already linked");
}
```
в
```ts
// fix if user integrated this shikimori account on another user account
```
