### ISSUE TITLE
Встал вопрос на клубнику🍓

### ISSUE THREAD

**Issue by TheaseMeanse** [Thenk0/LitminkaApi#57]
Итак, команда разработчиков, встал большой вопрос красного цвета. Что делать с проном и его последствиями?
Апи шики имеет параметр censored и параметр фильтрации по рейтингу, которые взаимоисключающие.
Надо разобраться, каким методом фильтровать🍓и другие фрукты, и как вообще быть с Rx/R+ контентом.

**Comment by Thenk0** [comment]
Refs: #12

**Comment by ArcKontyR** [comment]
Предложения:
1. Добавлять в базу все аниме независимо от цензуры
2. Ставить метку о 🍑 на тайтлы в которых есть жанры: хентай, яой, юри, сёдзе-ай, сёнен-ай

**Comment by TheaseMeanse** [comment]
Также можно фильтровать тайтлы жанра эротика для незарегистрированных пользователей

**Comment by Thenk0** [comment]
Мое предложение, явно отсеивать тайтлы с Rx рейтингом, т.к это точно всегда прон

**Comment by Thenk0** [comment]
Refs: #58 В GraphQL апи есть возможность доставать параметр isCensored, тем самым можно будет фильтровать аниме у нас, игнорировать остальное

**Comment by TheaseMeanse** [comment]
Итоговое решение:
 1. Для полноты списков записываем в базу всё (включая RX тайтлы)
 2. Поле `isCensored` считается автоматически зацензуренным
 3. При наличии лицензии в РФ уходит в статус забаненных в РФ
 4. При наличии жанров сенён-ай, сёдзе-ай, юри и яой уходит в статус забаненных в РФ
 5. При наличии жанров хентай, юри и яой автоматически считается зацензуренным (удовлетворяется пунктом 2)
 6. На главной странице сайта будет действовать мягкий бан на контент жанров: этти, эротика, сенён-ай, сёдзе-ай (отключаемая в настройках)

Памятка:
 1. Бан тайтла - тайтл заблокирован по геолокации для РФ региона
 2. Цензура тайтла - тайтл отображается на сайте только при снятом флаге в профиле, также не отображается у незарегистрированных пользователей
