### ISSUE TITLE
Разгрести импортовый ад в файлах

### ISSUE THREAD

**Issue by Thenk0** [Thenk0/LitminkaApi#64]
Создать алиасы основных путей в тсконфиге
Пример
```ts
import { Button } from '@components/button';
```
```json
{
  "compilerOptions": {
    "paths": {
      "@/*": ["./src/*"]
    }
  }
}
```
[Источник](https://blog.logrocket.com/using-path-aliases-cleaner-react-typescript-imports/), [Документация тса по путям](https://www.typescriptlang.org/tsconfig#paths)

**Comment by ArcKontyR** [comment]
[Возможная помощь для Node.js](https://dev.to/larswaechter/path-aliases-with-typescript-in-nodejs-4353)
